site_name: ğŸš€ LeetPatterns

nav:
  - ğŸ  Home: README.md

  - ğŸ§© Array: array.md
  - ğŸ” Binary Search: binary_search.md
  - â© Fast Slow Pointers: fast_slow_pointers.md
  - â© Left Right Pointers: left_right_pointers.md
  - ğŸªŸ Sliding Window Fixed: sliding_window_fixed.md
  - ğŸªŸ Sliding Window Variable: sliding_window_variable.md
  - ğŸ§® Prefix Sum: prefix_sum.md

  - ğŸ”¢ Hash Map: hash_map.md
  - ğŸ”¢ Hash Set: hash_set.md
  - ğŸ”¢ Hash Counting: hash_counting.md

  - ğŸ”— Linked List: linked_list.md

  - ğŸŒ³ Tree Traversal: tree_traversal.md
  - ğŸŒ³ Tree Feature: tree_feature.md
  - ğŸŒ³ Tree BFS: tree_bfs.md
  - ğŸŒ³ Tree Modification: tree_modification.md
  - ğŸŒ³ Tree BST: tree_bst.md
  - ğŸŒ³ Tree Common Ancestor: tree_common_ancestor.md
  - ğŸŒ³ Tree Trie: tree_trie.md

  - ğŸ“š Stack: stack.md
  - ğŸ“š Stack Monotonic: stack_monotonic.md
  - ğŸ“š Queue: queue.md

  - ğŸ¤‘ Greedy: greedy.md
  - ğŸ¤‘ Greedy Interval: greedy_interval.md

  - â³ DP Basic: dp_basic.md
  - â³ DP 2D: dp_2d.md
  - â³ DP Interval: dp_interval.md
  - â³ DP Knapsack 0/1: dp_knapsack_01.md
  - â³ DP Knapsack Unbounded: dp_knapsack_unbounded.md
  - â³ DP Kadane: dp_kadane.md
  - â³ DP Stock: dp_stock.md
  - â³ DP LCS: dp_lcs.md
  - â³ DP LIS: dp_lis.md

  - ğŸ”„ Backtracking Combinations: backtracking_combinations.md
  - ğŸ”„ Backtracking Permutations: backtracking_permutations.md
  - ğŸ”„ Backtracking Subsets: backtracking_subsets.md
  - ğŸ”„ Backtracking Partitions: backtracking_partitions.md
  - ğŸ”„ Backtracking Board: backtracking_board.md

  - ğŸ“ Graph Flood Fill: graph_flood_fill.md
  - ğŸ“ Graph Topological Sort: graph_topological_sort.md
  - ğŸ“ Graph Union Find: graph_union_find.md

  - ğŸ–‡ Heap Top K: heap_top_k.md
  - ğŸ–‡ Heap Two Heaps: heap_two_heaps.md
  - ğŸ–‡ Heap Merge K Sorted: heap_merge_k_sorted.md

  - ğŸ· Design: design.md

##############################################
##  Material theme configuration for MkDocs ##
##############################################

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        accent: pink
  font:
    text: Open Sans
    code: Roboto Mono
  features:
    - content.code.copy
    - content.code.select
    # - navigation.tabs
    - navigation.indexes # Enable indexes for the navigation
    - search.suggest # Enable search suggestions
    - content.math

markdown_extensions:
  - pymdownx.snippets:
      base_path: docs/snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
