site_name: ğŸš€LeetPattern
site_url: https://www.leetpattern.com
site_author: Sihan A
site_description: LeetCode Patterns
repo_url: https://github.com/russhustle/leetpattern/

nav:
  - Home: README.md
  - Coding:
      - Home: coding/index.md
      - ğŸ§© Arrays:
          - Home: arrays/index.md
          - Array: arrays/array.md
          - Binary Search: arrays/binary_search.md
          - Fast Slow Pointers: arrays/fast_slow_pointers.md
          - Left Right Pointers: arrays/left_right_pointers.md
          - Sliding Window Fixed: arrays/sliding_window_fixed.md
          - Sliding Window Variable: arrays/sliding_window_variable.md
          - Prefix Sum: arrays/prefix_sum.md

      - ğŸ”¢ Hash:
          - Hash Map: hash_map.md
          - Hash Set: hash_set.md
          - Counting: hash_counting.md

      - ğŸ’¬ String:
          - String: string.md
          - KMP: string_kmp.md

      - ğŸ”— Linked List: linkedlist/linked_list.md

      - ğŸŒ³ Tree:
          - Tree: tree/index.md
          - Traversal: tree_traversal.md
          - Tree Feature: tree_feature.md
          - Tree BFS: tree_bfs.md
          - Tree Modification: tree_modification.md
          - BST: tree_bst.md
          - Common Ancestors: tree_common_ancestor.md
          - Trie: tree_trie.md

      - ğŸ“š Stack & Queue:
          - Stack: stack.md
          - Monotonic Stack: stack_monotonic.md
          - Queue: queue.md

      - ğŸ¤‘ Greedy:
          - Greedy: greedy.md
          - Greedy - Interval: greedy_interval.md

      - â³ Dynamic Programming:
          - Home: dp/index.md
          - DP Basic: dp/dp_basic.md
          - DP 2D: dp/dp_2d.md
          - DP Interval: dp/dp_interval.md
          - Knapsack 0/1: dp/dp_knapsack_01.md
          - Knapsack Unbounded: dp/dp_knapsack_unbounded.md
          - Kadane: dp/dp_kadane.md
          - Stock: dp/dp_stock.md
          - LCS: dp/dp_lcs.md
          - LIS: dp/dp_lis.md

      - ğŸ”„ Backtracking:
          - Home: backtracking/index.md
          - Combinations: backtracking/backtracking_combinations.md
          - Permutations: backtracking/backtracking_permutations.md
          - Subsets: backtracking/backtracking_subsets.md
          - Partitions: backtracking/backtracking_partitions.md
          - Board: backtracking/backtracking_board.md

      - ğŸ“ Graph:
          - Graph: graph/index.md
          - Flood Fill: graph/graph_flood_fill.md
          - DFS: graph/graph_dfs.md
          - BFS: graph/graph_bfs.md
          - Topological Sort: graph/graph_topological_sort.md
          - Union Find: graph/graph_union_find.md
          - Shortest Path: graph/graph_shortest_path.md
          - Bellman Ford: graph/graph_bellman_ford.md
          - MST: graph/graph_mst.md
          - Coloring: graph/graph_coloring.md

      - ğŸ”ï¸ Heap:
          - Home: heap/index.md
          - Heap: heap/heap_heap.md
          - Top K: heap/heap_top_k.md
          - Two Heaps: heap/heap_two_heaps.md
          - Merge K Sorted: heap/heap_merge_k_sorted.md

      - ğŸ Other:
          - ğŸ© Bit: bit.md

      - ğŸ‘¨ğŸ»â€ğŸ’» Neetcode 150:
          - Home: neetcode150/index.md
          - Arrays & Hashing: neetcode150/arrays_hashing.md
          - Two Pointers: neetcode150/two_pointers.md
          - Sliding Window: neetcode150/sliding_window.md
          - Stack: neetcode150/stack.md
          - Binary Search: neetcode150/binary_search.md
          - Linked List: neetcode150/linked_list.md
          - Trees: neetcode150/trees.md
          - Heap: neetcode150/heap.md
          - Backtracking: neetcode150/backtracking.md
          - Tries: neetcode150/tries.md
          - Graphs: neetcode150/graphs.md
          - Advanced Graphs: neetcode150/advanced_graphs.md
          - 1D Dynamic Programming: neetcode150/1d_dynamic_programming.md
          - 2D Dynamic Programming: neetcode150/2d_dynamic_programming.md
          - Greedy: neetcode150/greedy.md
          - Intervals: neetcode150/intervals.md
          - Math & Geometry: neetcode150/math_geometry.md
          - Bit Manipulation: neetcode150/bit.md

      # - ğŸ Python:
      #     - Home: python/index.md
      #     - collections: python/python_collections.md

  - OOD:
      # - ğŸŠ Design Patterns: design_patterns.md
      - ğŸš  Design: design.md

  - Challenges:
      - Home: challenge/index.md
      - 2024 September: challenge/202409.md
      - 2024 September CN: challenge/202409_cn.md

##############################################
##  Material theme configuration for MkDocs ##
##############################################

theme:
  logo: imgs/logo.jpg
  favicon: imgs/logo.jpg
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.indexes # Enable indexes for the navigation
    - search.suggest # Enable search suggestions
    - search.highlight # Enable search term highlighting
    - content.math
    - grid

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs/snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex: # latex support
      generic: true
  - toc:
      permalink: true # Add permalinks to headers
  - attr_list
  - md_in_html

plugins:
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: timeago
  - search

extra:
  creator: Sihan A
  homepage: https://www.leetpattern.com
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sihan-A
      name: GitHub | Sihan A
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sihan-a/
      name: LinkedIn | Sihan A
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/sihana
      name: Kaggle | Sihan A
    - icon: fontawesome/brands/medium
      link: https://medium.com/@sihan-a
      name: Medium | Sihan A

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/no-footer.css
  - css/unordered-list-symbols.css
  - css/ordered-list-symbols.css
